NAME: moai_eval.yaml

DATASETS:
  TRAIN: ""
  TEST: ""
  SIZE_DIVISIBILITY: 32
  PROPOSAL_FILES_TRAIN: []

# OPTIMIZER
OPTIMIZER:
  LR: 2e-5 # LR
  LAST_LR: 1e-6 # LAST LR
  PERIOD: 10 # Save Period
  WEIGHT_DECAY: 0 # Weight Decay
  EPOCH: 1 # epoch
  GRAD_MAX: 10
  GRAD_CUM: 1 # Gradient Accumulation

# MoAI LLM
LLM:
  LOAD_LLM: true # LLM
  BITS: 4 # bit quantization
  GRAD_CKPT: false # Gradient Checkpointing
  LORA: false # Low Rank Adaptation
  DTYPE: 'fp16' # dtype

# Define Test/Trainer/Saving
PIPELINE: MoAIPipeline
SAVE_DIR: ''
base_path: "./"

# Resume Logistic
RESUME: false
WEIGHT: false
RESET_DATA_LOADER: false
RESUME_FROM: ''
EVAL_AT_START: False

# Logging and Debug
WANDB: False

MODEL:
  NAME: moai_model
  MASK_ON: false
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  DECODER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: True
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false

INPUT:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 16
  LOAD_PROPOSALS: False
  SAMPLER_TRAIN: "TrainingSampler"
  ASPECT_RATIO_GROUPING: True

# TextVQA Dataset
TEXTVQA:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "gqa"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# ScienceQA Dataset
SCIENCEQA:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "scienceqa"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# POPE Dataset
POPE:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "pope"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True


# MME Dataset
MME:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "mme"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# MMBench Dataset
MMBENCH:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "mmbench"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True


# QBench Dataset
QBENCH:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "qbench"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# MM-VET Dataset
MMVET:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "mmvet"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# MATHVISTA Dataset
MATHVISTA:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "mathvista"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# AI2D Dataset
AI2D:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "ai2d"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True


# HALLUSIONBENCH Dataset
HALLUSIONBENCH:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "hallusionbench"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True

# SEED Dataset
SEED:
  INPUT:
    IMAGE_SIZE: 490
    DATASET_MAPPER_NAME: "seed"
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    CROP:
      ENABLED: True
    NUM_CLASSES: 3129
  TEST:
    BATCH_SIZE_TOTAL: 1
    TEMPERATURE: 0
    TOP_P: None
    NUM_BEAMS: 1
    MAX_NEW_TOKENS: 128
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 16
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: True
